//! Definitions from `luaconf.h`.

pub use super::glue::{LUA_VDIR, LUA_PATH_DEFAULT, LUA_CPATH_DEFAULT, LUA_DIRSEP, LUA_EXTRASPACE,
                      LUA_IDSIZE, LUAI_MAXSHORTLEN, LUA_KCONTEXT, LUAI_BITSINT, LUAI_MAXSTACK,
                      LUAL_BUFFERSIZE, LUA_NUMBER, LUA_UNSIGNED, LUA_INTEGER, LUA_MAXINTEGER,
                      LUA_MININTEGER};
